### ISSUE TITLE
Questions about the project

### ISSUE THREAD

**Issue by kasterby** [othermod/PSPi-Version-6#24]
Hello, 

A few questions for @othermod, if you are enclined to answer of course!

- Do you plan to replace the microUSB port with a type C connector (I guess that would be desctructive)
- Is there a roadmap available, and a status for the eventual version 7?

Thank you for your awesome work!

**Comment by othermod** [comment]
- Nope, no plans to swap the USB to a type C. I don't want this to require case or LCD bracket cutting.
- I've shipped a few hundred boards since the beginning of the year, and there are around 3000 people who want to buy this, so I'll be totally consumed by that for a while.

If there ever is a version 7 or whatever, I lean toward making a custom shell with usb c and other things. Not sure though, and things may change over time.

**Comment by kasterby** [comment]
Thanks!
