### ISSUE TITLE
How to Transfer ROMs to a non Wifi CM4 module

### ISSUE THREAD

**Issue by Mr-JimmyDeath** [othermod/PSPi-Version-6#27]
Hello

Have built my own PSPi 6 which works great with a Zero 2 W however when I switch to a CM4 module I can't work out how to transfer ROMs onto the card. I have tried plugging the PSPi into a PC  hoping it would appear as a drive but sadly not. Would the USB stick method work if I can get an adaptor to plug it into the PSPi mini USB socket?  Is there a better method?

Thanks, Regards

james

**Comment by MakeOrBreakSociety** [comment]
the process should be exactly the same as it was with the Zero.  connect it to the internet and type \\xxx.xxx.xxx.xxx into a file explorer window (replace x with the IP of your PSPi)

**Comment by MakeOrBreakSociety** [comment]
sorry I just deleted my comment because I had forgotten how to read titles. :)

you can use a usb mini b to a adapter and connect a flash drive.  the method to transfer the files will depend on the operating system your running.  

The other option (and the one I use on my Pi Zero without wifi) is to connect a usb wifi stick to the pspi so you can transfer over the network :)

**Comment by Mr-JimmyDeath** [comment]
Thanks for the quick response, I'll order an adapter.

:)
